#define NOB_IMPLEMENTATION
#include "nob.h"

#include <errno.h>

#if defined(_WIN32)
#include <direct.h>
#define NOC_EXE ".exe"
#else
#define NOC_EXE ""
#endif

#define NOC_FUZZ "build/noc-fuzz" NOC_EXE
#define NOC_EMBED_DIALECT "build/embed-dialect" NOC_EXE
#define NOC_EMBED_EXAMPLE "build/embed-example" NOC_EXE
#define NOC_RULES_DIALECT "build/rules-dialect" NOC_EXE
#define NOC_RULES_EXAMPLE "build/rules-example" NOC_EXE
#define NOC_IDE_EXAMPLE "build/ide-example" NOC_EXE
#define NOC_GENERATED_HEADER "build/generated/noc.h"

static const char *header_sources[] = {
    "src/noc.h",
};

typedef struct {
    const char *key;
    const char *source;
    const char *output;
    bool compile_as_cpp;
} Test_Suite;

static const Test_Suite test_suites[] = {
    {"header-c", "tests/test_header.c", "build/noc-test-header-c" NOC_EXE, false},
    {"header-cpp", "tests/test_header.c", "build/noc-test-header-cpp" NOC_EXE, true},
    {"lexing", "tests/test_lexing.c", "build/noc-test-lexing" NOC_EXE, false},
    {"syntax", "tests/test_syntax.c", "build/noc-test-syntax" NOC_EXE, false},
    {"c-analysis", "tests/test_c_analysis.c", "build/noc-test-c-analysis" NOC_EXE, false},
    {"rewriter", "tests/test_rewriter.c", "build/noc-test-rewriter" NOC_EXE, false},
    {"artifacts", "tests/test_artifacts.c", "build/noc-test-artifacts" NOC_EXE, false},
};

#if !defined(_MSC_VER) || defined(__clang__)
static const char *compiler(void)
{
    const char *cc = getenv("CC");
    return cc && cc[0] ? cc : "cc";
}

static const char *cpp_compiler(void)
{
    const char *cxx = getenv("CXX");
    return cxx && cxx[0] ? cxx : "c++";
}
#endif

static bool ensure_build_directories(void)
{
    return nob_mkdir_if_not_exists("build") &&
           nob_mkdir_if_not_exists("build/generated") &&
           nob_mkdir_if_not_exists("build/generated/ide");
}

static int output_rebuild_state(const char *output,
                                const char **inputs,
                                size_t inputs_count)
{
    int result = nob_needs_rebuild(output, inputs, inputs_count);
    if (result < 0) {
        nob_log(NOB_ERROR, "could not determine whether %s needs rebuilding", output);
    }
    return result;
}

static bool verify_generated_file(const char *actual_path, const char *expected_path)
{
    Nob_String_Builder actual = {0};
    Nob_String_Builder expected = {0};
    bool ok = false;
    if (!nob_read_entire_file(actual_path, &actual) ||
        !nob_read_entire_file(expected_path, &expected)) {
        goto done;
    }
    ok = actual.count == expected.count &&
         (actual.count == 0 || memcmp(actual.items, expected.items, actual.count) == 0);
    if (!ok) {
        nob_log(NOB_ERROR, "%s differs from %s", actual_path, expected_path);
    }

done:
    nob_sb_free(actual);
    nob_sb_free(expected);
    return ok;
}

static bool build_header_contents(Nob_String_Builder *header)
{
    static const char banner[] =
        "/* Generated by `./nob header` from the sources listed in nob.c.\n"
        "   Do not edit this file directly. */\n\n";
    size_t i;
    nob_sb_append_buf(header, banner, sizeof(banner) - 1);
    for (i = 0; i < NOB_ARRAY_LEN(header_sources); ++i) {
        Nob_String_Builder source = {0};
        if (!nob_read_entire_file(header_sources[i], &source)) {
            nob_sb_free(source);
            return false;
        }
        nob_sb_append_buf(header, source.items, source.count);
        if (source.count > 0 && source.items[source.count - 1] != '\n') {
            nob_sb_append(header, '\n');
        }
        nob_sb_free(source);
    }
    return true;
}

static bool header_matches(const char *path, const Nob_String_Builder *expected)
{
    Nob_String_Builder actual = {0};
    bool matches;
    if (nob_file_exists(path) <= 0) return false;
    matches = nob_read_entire_file(path, &actual) &&
              actual.count == expected->count &&
              (actual.count == 0 ||
               memcmp(actual.items, expected->items, actual.count) == 0);
    nob_sb_free(actual);
    return matches;
}

static bool generate_header(const char *path)
{
    Nob_String_Builder generated = {0};
    bool ok = build_header_contents(&generated);
    if (!ok) goto done;
    if (!header_matches(path, &generated)) {
        ok = nob_write_entire_file(path, generated.items, generated.count);
        if (ok) nob_log(NOB_INFO, "generated %s", path);
    }

done:
    nob_sb_free(generated);
    return ok;
}

static bool verify_release_header(void)
{
    Nob_String_Builder first = {0};
    Nob_String_Builder second = {0};
    bool ok = build_header_contents(&first) && build_header_contents(&second);
    if (ok &&
        (first.count != second.count ||
         (first.count != 0 && memcmp(first.items, second.items, first.count) != 0))) {
        nob_log(NOB_ERROR, "header generation is not deterministic");
        ok = false;
    }
    if (ok && !header_matches("noc.h", &first)) {
        nob_log(NOB_ERROR, "noc.h is stale; run ./nob header");
        ok = false;
    }
    nob_sb_free(first);
    nob_sb_free(second);
    return ok;
}

static bool prepare_generated_header(void)
{
    return generate_header(NOC_GENERATED_HEADER);
}

static void append_compile_command(Nob_Cmd *command,
                                   const char *output,
                                   const char *source,
                                   bool compile_as_cpp)
{
#if defined(_MSC_VER) && !defined(__clang__)
    nob_cmd_append(command,
                   "cl.exe",
                   compile_as_cpp ? "/std:c++14" : "/std:c11",
                   "/W4",
                   "/WX",
                   "/nologo",
                   "/D_CRT_SECURE_NO_WARNINGS",
                   compile_as_cpp ? "/TP" : "/TC",
                   "/Ibuild/generated",
                   "/I.",
                   nob_temp_sprintf("/Fe:%s", output),
                   nob_temp_sprintf("/Fo:%s.obj", output),
                   source);
#else
    nob_cmd_append(command,
                   compile_as_cpp ? cpp_compiler() : compiler(),
                   compile_as_cpp ? "-std=c++11" : "-std=c11",
                   "-Wall",
                   "-Wextra",
                   "-Wpedantic",
                   "-Werror",
                   "-Ibuild/generated",
                   "-I.",
                   "-x",
                   compile_as_cpp ? "c++" : "c",
                   "-o",
                   output,
                   source);
#endif
}

static bool build_binary(const char *output, const char *source)
{
    const char *inputs[] = {source, NOC_GENERATED_HEADER, "nob.c"};
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state(output, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) {
        return nob_file_exists(output) > 0;
    }
    append_compile_command(&command, output, source, false);
    return nob_cmd_run(&command);
}

static bool build_test_suite(const Test_Suite *suite)
{
    const char *inputs[] = {
        suite->source,
        "tests/test_support.h",
        NOC_GENERATED_HEADER,
        "nob.c",
    };
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state(suite->output, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) return nob_file_exists(suite->output) > 0;
    append_compile_command(&command,
                           suite->output,
                           suite->source,
                           suite->compile_as_cpp);
    return nob_cmd_run(&command);
}

static bool run_test_suite(const Test_Suite *suite)
{
    Nob_Cmd command = {0};
    if (!build_test_suite(suite)) return false;
    nob_cmd_append(&command, suite->output);
    return nob_cmd_run(&command);
}

static const Test_Suite *find_test_suite(const char *key)
{
    size_t i;
    for (i = 0; i < NOB_ARRAY_LEN(test_suites); ++i) {
        if (strcmp(test_suites[i].key, key) == 0) return &test_suites[i];
    }
    return NULL;
}

static void print_test_suites(void)
{
    size_t i;
    fprintf(stderr, "Valid test suites:");
    for (i = 0; i < NOB_ARRAY_LEN(test_suites); ++i) {
        fprintf(stderr, " %s", test_suites[i].key);
    }
    fputc('\n', stderr);
}

static bool build_fuzz(void)
{
    return build_binary(NOC_FUZZ, "tests/fuzz_noc.c");
}

static bool build_embed_dialect(void)
{
    return build_binary(NOC_EMBED_DIALECT, "examples/embed/dialect.c");
}

static bool generate_embed_example(void)
{
    const char *output = "build/generated/embed_app.c";
    const char *depfile = "build/generated/embed_app.d";
    const char *inputs[] = {
        "examples/embed/app.c",
        "examples/embed/message.txt",
        NOC_EMBED_DIALECT,
        "nob.c",
    };
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state(output, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild != 0 || nob_file_exists(depfile) <= 0) {
        nob_cmd_append(&command,
                       NOC_EMBED_DIALECT,
                       "examples/embed/app.c",
                       "-o",
                       output,
                       "--depfile",
                       depfile);
        if (!nob_cmd_run(&command)) return false;
    }
    return nob_file_exists(output) > 0 &&
           verify_generated_file(depfile, "tests/golden/embed_app.d");
}

static bool build_embed_example(void)
{
    const char *inputs[] = {"build/generated/embed_app.c", "nob.c"};
    Nob_Cmd command = {0};
    int rebuild;
    if (!build_embed_dialect() || !generate_embed_example()) return false;
    rebuild = output_rebuild_state(NOC_EMBED_EXAMPLE, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) {
        return nob_file_exists(NOC_EMBED_EXAMPLE) > 0;
    }
    append_compile_command(&command,
                           NOC_EMBED_EXAMPLE,
                           "build/generated/embed_app.c",
                           false);
    return nob_cmd_run(&command);
}

static bool build_rules_dialect(void)
{
    return build_binary(NOC_RULES_DIALECT, "examples/rules/dialect.c");
}

static bool generate_rules_example(void)
{
    const char *inputs[] = {
        "examples/rules/app.c",
        NOC_RULES_DIALECT,
        "nob.c",
    };
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state("build/generated/rules_app.c",
                                       inputs,
                                       NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) {
        return nob_file_exists("build/generated/rules_app.c") > 0;
    }
    nob_cmd_append(&command,
                   NOC_RULES_DIALECT,
                   "examples/rules/app.c",
                   "-o",
                   "build/generated/rules_app.c");
    return nob_cmd_run(&command);
}

static bool build_rules_example(void)
{
    const char *inputs[] = {"build/generated/rules_app.c", "nob.c"};
    Nob_Cmd command = {0};
    int rebuild;
    if (!build_rules_dialect() || !generate_rules_example()) return false;
    rebuild = output_rebuild_state(NOC_RULES_EXAMPLE, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) {
        return nob_file_exists(NOC_RULES_EXAMPLE) > 0;
    }
    append_compile_command(&command,
                           NOC_RULES_EXAMPLE,
                           "build/generated/rules_app.c",
                           false);
    return nob_cmd_run(&command);
}

static bool generate_ide_overlays(void)
{
    const char *app_output = "build/generated/ide/app.c";
    const char *header_output = "build/generated/ide/math.h";
    const char *inputs[] = {
        "examples/ide/app.c",
        "examples/ide/math.h",
        NOC_RULES_DIALECT,
        "nob.c",
    };
    Nob_Cmd command = {0};
    int app_rebuild = output_rebuild_state(app_output, inputs, NOB_ARRAY_LEN(inputs));
    int header_rebuild = output_rebuild_state(header_output,
                                              inputs,
                                              NOB_ARRAY_LEN(inputs));
    if (app_rebuild < 0 || header_rebuild < 0) return false;
    if (app_rebuild != 0 || header_rebuild != 0 ||
        nob_file_exists("build/generated/ide/app.c.d") <= 0 ||
        nob_file_exists("build/generated/ide/math.h.d") <= 0) {
        nob_cmd_append(&command,
                       NOC_RULES_DIALECT,
                       "--batch-depfiles",
                       "examples/ide",
                       "build/generated/ide",
                       "examples/ide/app.c",
                       "examples/ide/math.h");
        if (!nob_cmd_run(&command)) return false;
    }
    return nob_file_exists(app_output) > 0 && nob_file_exists(header_output) > 0;
}

static bool generate_ide_metadata(void)
{
    const char *output = "build/generated/ide/rules_metadata.h";
    const char *inputs[] = {NOC_RULES_DIALECT, "nob.c"};
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state(output, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) return nob_file_exists(output) > 0;
    nob_cmd_append(&command, NOC_RULES_DIALECT, "--ide-metadata", output);
    return nob_cmd_run(&command);
}

static bool generate_ide_command_signature(void)
{
    const char *output = "build/generated/ide/compile.sig";
    const char *inputs[] = {NOC_RULES_DIALECT, "nob.c"};
    Nob_Cmd command = {0};
    int rebuild = output_rebuild_state(output, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild != 0) {
        nob_cmd_append(&command,
                       NOC_RULES_DIALECT,
                       "--command-signature",
                       output,
                       "--",
                       "cc",
                       "-std=c11",
                       "-Ibuild/generated/ide",
                       "-c",
                       "build/generated/ide/app.c");
        if (!nob_cmd_run(&command)) return false;
    }
    return verify_generated_file(output, "tests/golden/ide_command.sig");
}

static bool build_ide_example(void)
{
    const char *output_source = "build/generated/ide/app.c";
    const char *output_header = "build/generated/ide/math.h";
    const char *metadata = "build/generated/ide/rules_metadata.h";
    const char *signature = "build/generated/ide/compile.sig";
    const char *inputs[] = {
        output_source,
        output_header,
        metadata,
        signature,
        "nob.c",
    };
    Nob_Cmd command = {0};
    int rebuild;
    if (!build_rules_dialect() ||
        !generate_ide_overlays() ||
        !generate_ide_metadata() ||
        !verify_generated_file(metadata, "tests/golden/rules_metadata.h") ||
        !generate_ide_command_signature()) {
        return false;
    }
    rebuild = output_rebuild_state(NOC_IDE_EXAMPLE, inputs, NOB_ARRAY_LEN(inputs));
    if (rebuild < 0) return false;
    if (rebuild == 0) return nob_file_exists(NOC_IDE_EXAMPLE) > 0;
    append_compile_command(&command, NOC_IDE_EXAMPLE, output_source, false);
    return nob_cmd_run(&command);
}

static bool remove_build_entry(Nob_Walk_Entry entry)
{
    int result;
#ifdef _WIN32
    result = entry.type == NOB_FILE_DIRECTORY ? _rmdir(entry.path) : remove(entry.path);
#else
    result = remove(entry.path);
#endif
    if (result != 0) {
        nob_log(NOB_ERROR, "could not remove %s: %s", entry.path, strerror(errno));
        return false;
    }
    return true;
}

static bool clean(void)
{
    if (nob_file_exists("build") == 0) return true;
    return nob_walk_dir("build", remove_build_entry, .post_order = true);
}

static void usage(const char *program)
{
    fprintf(stderr,
            "Usage: %s [test [suite]|fuzz|example|describe|header|verify-header|clean]\n",
            program);
}

int main(int argc, char **argv)
{
    const char *target = argc > 1 ? argv[1] : "test";
    NOB_GO_REBUILD_URSELF(argc, argv);

    if (strcmp(target, "clean") == 0) return clean() ? 0 : 1;
    if (!ensure_build_directories()) return 1;
    if (strcmp(target, "header") == 0) {
        return generate_header("noc.h") && prepare_generated_header() ? 0 : 1;
    }
    if (strcmp(target, "verify-header") == 0) {
        return verify_release_header() ? 0 : 1;
    }
    if (!prepare_generated_header()) return 1;

    if (strcmp(target, "test") == 0) {
        Nob_Cmd command = {0};
        size_t i;
        if (argc > 2) {
            const Test_Suite *suite = find_test_suite(argv[2]);
            if (!suite) {
                fprintf(stderr, "Unknown test suite: %s\n", argv[2]);
                print_test_suites();
                return 2;
            }
            return run_test_suite(suite) ? 0 : 1;
        }
        for (i = 0; i < NOB_ARRAY_LEN(test_suites); ++i) {
            if (!run_test_suite(&test_suites[i])) return 1;
        }
        if (!build_fuzz() || !build_embed_example() || !build_rules_example() ||
            !build_ide_example()) return 1;
        nob_cmd_append(&command, NOC_FUZZ);
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_EMBED_EXAMPLE);
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_RULES_EXAMPLE);
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_IDE_EXAMPLE);
        return nob_cmd_run(&command) ? 0 : 1;
    }
    if (strcmp(target, "fuzz") == 0) {
        Nob_Cmd command = {0};
        if (!build_fuzz()) return 1;
        nob_cmd_append(&command, NOC_FUZZ);
        return nob_cmd_run(&command) ? 0 : 1;
    }
    if (strcmp(target, "example") == 0) {
        Nob_Cmd command = {0};
        if (!build_embed_example() || !build_rules_example() || !build_ide_example()) return 1;
        nob_cmd_append(&command, NOC_EMBED_EXAMPLE);
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_RULES_EXAMPLE);
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_IDE_EXAMPLE);
        return nob_cmd_run(&command) ? 0 : 1;
    }
    if (strcmp(target, "describe") == 0) {
        Nob_Cmd command = {0};
        if (!build_embed_dialect() || !build_rules_dialect()) return 1;
        nob_cmd_append(&command, NOC_EMBED_DIALECT, "--describe");
        if (!nob_cmd_run(&command)) return 1;
        nob_cmd_append(&command, NOC_RULES_DIALECT, "--describe");
        return nob_cmd_run(&command) ? 0 : 1;
    }

    usage(argv[0]);
    return 2;
}
