#include "test_support.h"

static bool expand_twice(Noc_Rewriter *rewriter,
                         const Noc_Rule *rule,
                         void *user_data)
{
    Noc_Slice expression;
    (void)rule;
    (void)user_data;
    if (!noc_rw_capture_balanced(rewriter, "(", ")", &expression)) return false;
    return noc_rw_emit_cstr(rewriter, "((") &&
           noc_rw_emit_slice(rewriter, expression) &&
           noc_rw_emit_cstr(rewriter, ") + (") &&
           noc_rw_emit_slice(rewriter, expression) &&
           noc_rw_emit_cstr(rewriter, "))");
}

static bool expand_static_attribute(Noc_Rewriter *rewriter,
                                    const Noc_Rule *rule,
                                    void *user_data)
{
    (void)rule;
    (void)user_data;
    return noc_rw_emit_cstr(rewriter, "static");
}

static void test_ide_metadata_header(void)
{
    Noc_Context context;
    Noc_Buffer generated = {0};
    Noc_Buffer defaults = {0};
    Diagnostic_State diagnostics = {0};
    Noc_Ide_Metadata_Options options = {
        "SAMPLE_DIALECT_METADATA_H",
        "SAMPLE_DIALECT",
        "sample?\" dialect",
        true,
    };
    Noc_Rule rule = {
        "twice",
        NOC_RULE_EXPRESSION,
        "@twice(line\n?)",
        "Duplicate \"values\"\tcarefully?",
        expand_twice,
        NULL,
    };
    char *preserved_items;
    size_t preserved_count;

    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    CHECK(noc_register_rule(&context, rule));
    CHECK(noc_generate_ide_metadata_header(&context, &options, &generated));
    CHECK(generated.items != NULL && generated.items[generated.count] == '\0');
    CHECK(strstr(generated.items, "#ifndef SAMPLE_DIALECT_METADATA_H\n") != NULL);
    CHECK(strstr(generated.items, "#define SAMPLE_DIALECT_SCHEMA_VERSION 1\n") != NULL);
    CHECK(strstr(generated.items,
                 "#define SAMPLE_DIALECT_DIALECT_NAME \"sample\\?\\\" dialect\"\n") != NULL);
    CHECK(strstr(generated.items, "#define SAMPLE_DIALECT_RULE_COUNT 1\n") != NULL);
    CHECK(strstr(generated.items, "#define SAMPLE_DIALECT_RULE_0_NAME \"twice\"\n") != NULL);
    CHECK(strstr(generated.items, "#define SAMPLE_DIALECT_RULE_0_SCOPE 1\n") != NULL);
    CHECK(strstr(generated.items,
                 "#define SAMPLE_DIALECT_RULE_0_SCOPE_NAME \"expression\"\n") != NULL);
    CHECK(strstr(generated.items,
                 "#define SAMPLE_DIALECT_RULE_0_SYNTAX \"@twice(line\\n\\?)\"\n") != NULL);
    CHECK(strstr(generated.items, "_DESCRIPTION") == NULL);

    CHECK(noc_buffer_append_cstr(&defaults, "old contents"));
    CHECK(noc_generate_ide_metadata_header(&context, NULL, &defaults));
    CHECK(strncmp(defaults.items,
                  "/* Generated by noc.h " NOC_VERSION,
                  sizeof("/* Generated by noc.h " NOC_VERSION) - 1) == 0);
    CHECK(strstr(defaults.items, "#ifndef NOC_IDE_METADATA_H_INCLUDED\n") != NULL);
    CHECK(strstr(defaults.items, "#define NOC_IDE_DIALECT_NAME \"project\"\n") != NULL);
    CHECK(strstr(defaults.items,
                 "#define NOC_IDE_RULE_0_DESCRIPTION "
                 "\"Duplicate \\\"values\\\"\\tcarefully\\?\"\n") != NULL);

    preserved_items = generated.items;
    preserved_count = generated.count;
    options.macro_prefix = "not-valid";
    CHECK(!noc_generate_ide_metadata_header(&context, &options, &generated));
    CHECK(diagnostics.errors == 1);
    CHECK(strstr(diagnostics.last_message, "C identifiers") != NULL);
    CHECK(generated.items == preserved_items && generated.count == preserved_count);

    noc_buffer_free(&defaults);
    noc_buffer_free(&generated);
    noc_context_deinit(&context);
}

static void test_depfile_generation(void)
{
    char *dependencies[] = {
        "src/my input.c",
        "C:\\sdk\\a b#$.h",
        "include/ordinary.h",
    };
    char *invalid_dependencies[] = {"include/bad\nname.h"};
    static const char expected[] =
        "build/my\\ output$$\\:obj.o: src/my\\ input.c "
        "C\\:\\\\sdk\\\\a\\ b\\#$$.h include/ordinary.h\n";
    Noc_Transform_Result result = {0};
    Noc_Transform_Result invalid = {0};
    Noc_Context context;
    Noc_Buffer output = {0};
    Diagnostic_State diagnostics = {0};
    char *preserved_items;
    size_t preserved_count;

    result.dependencies = dependencies;
    result.dependency_count = sizeof(dependencies) / sizeof(dependencies[0]);
    invalid.dependencies = invalid_dependencies;
    invalid.dependency_count = 1;
    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    CHECK(noc_generate_depfile(&context,
                               "build/my output$:obj.o",
                               "src/my input.c",
                               &result,
                               &output));
    CHECK(output.count == sizeof(expected) - 1);
    CHECK(memcmp(output.items, expected, sizeof(expected) - 1) == 0);
    CHECK(output.items[output.count] == '\0');

    preserved_items = output.items;
    preserved_count = output.count;
    CHECK(!noc_generate_depfile(&context,
                                "build/output.o",
                                "src/input.c",
                                &invalid,
                                &output));
    CHECK(diagnostics.errors == 1);
    CHECK(strstr(diagnostics.last_message, "cannot contain newlines") != NULL);
    CHECK(output.items == preserved_items && output.count == preserved_count);

    noc_buffer_free(&output);
    noc_context_deinit(&context);
}

static void test_command_signature(void)
{
    const char *arguments[] = {
        "cc",
        "-DNAME=a\nb",
        "",
        "C:\\Program Files\\cc",
    };
    const char *invalid_arguments[] = {"cc", NULL};
    static const char expected[] =
        "noc-command-signature 1\n"
        "noc-version 6:" NOC_VERSION "\n"
        "arguments 4\n"
        "argument 2:cc\n"
        "argument 10:-DNAME=a\nb\n"
        "argument 0:\n"
        "argument 19:C:\\Program Files\\cc\n";
    Noc_Context context;
    Noc_Buffer output = {0};
    Noc_Buffer empty = {0};
    Diagnostic_State diagnostics = {0};
    char *preserved_items;
    size_t preserved_count;

    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    CHECK(noc_generate_command_signature(&context,
                                         arguments,
                                         sizeof(arguments) / sizeof(arguments[0]),
                                         &output));
    CHECK(output.count == sizeof(expected) - 1);
    CHECK(memcmp(output.items, expected, sizeof(expected) - 1) == 0);
    CHECK(output.items[output.count] == '\0');
    CHECK(noc_generate_command_signature(&context, NULL, 0, &empty));
    CHECK(strstr(empty.items, "arguments 0\n") != NULL);

    preserved_items = output.items;
    preserved_count = output.count;
    CHECK(!noc_generate_command_signature(&context,
                                          invalid_arguments,
                                          sizeof(invalid_arguments) /
                                              sizeof(invalid_arguments[0]),
                                          &output));
    CHECK(diagnostics.errors == 1);
    CHECK(strstr(diagnostics.last_message, "cannot be NULL") != NULL);
    CHECK(output.items == preserved_items && output.count == preserved_count);

    noc_buffer_free(&empty);
    noc_buffer_free(&output);
    noc_context_deinit(&context);
}

static void test_batch_transformation(void)
{
    const char *inputs[] = {
        "examples/ide/app.c",
        "examples/ide/math.h",
    };
    const char *duplicates[] = {
        "examples/ide/app.c",
        "examples/ide/app.c",
    };
    const char *escaping[] = {"examples/ide/../ide/app.c"};
    const char *overlapping[] = {
        "tests/fixtures/batch-overlap/a.c",
        "tests/fixtures/batch-overlap/sub/a.c",
    };
    const char *late_invalid[] = {
        "examples/ide/app.c",
        "examples-other/not-under-root.c",
    };
    static const char app_depfile[] =
        "build/batch-api/ide/app.c: examples/ide/app.c\n";
    static const char header_depfile[] =
        "build/batch-api/ide/math.h: examples/ide/math.h\n";
    Noc_Batch_Options options = {"examples", "build/batch-api", true};
    Noc_Context context;
    Diagnostic_State diagnostics = {0};
    Noc_Rule square = {
        "square",
        NOC_RULE_EXPRESSION,
        "@square(expression)",
        "Test batch expression rule.",
        expand_twice,
        NULL,
    };
    Noc_Rule private_rule = {
        "private",
        NOC_RULE_ATTRIBUTE,
        "@private declaration",
        "Test batch attribute rule.",
        expand_static_attribute,
        NULL,
    };
    const char *paths[] = {
        "build/batch-api/ide/app.c",
        "build/batch-api/ide/math.h",
        "build/batch-api/ide/app.c.d",
        "build/batch-api/ide/math.h.d",
    };
    char contents[2048];
    size_t counts[4] = {0};
    size_t i;

    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    context.options.emit_line_directives = false;
    CHECK(noc_register_rule(&context, square));
    CHECK(noc_register_rule(&context, private_rule));
    CHECK(noc_transform_files(&context,
                              &options,
                              inputs,
                              sizeof(inputs) / sizeof(inputs[0])));
    for (i = 0; i < sizeof(paths) / sizeof(paths[0]); ++i) {
        FILE *file = fopen(paths[i], "rb");
        CHECK(file != NULL);
        if (file) {
            counts[i] = fread(contents, 1, sizeof(contents) - 1, file);
            CHECK(!ferror(file));
            CHECK(fclose(file) == 0);
            contents[counts[i]] = '\0';
            if (i < 2) CHECK(strchr(contents, '@') == NULL);
            if (i == 2) CHECK(slice_equals((Noc_Slice){contents, counts[i]}, app_depfile));
            if (i == 3) CHECK(slice_equals((Noc_Slice){contents, counts[i]}, header_depfile));
        }
    }
    CHECK(counts[0] > 0 && counts[1] > 0);

    options.input_root = "tests/fixtures/batch-overlap";
    options.output_root = "tests/fixtures/batch-overlap/sub";
    options.emit_depfiles = false;
    CHECK(!noc_transform_files(&context,
                               &options,
                               overlapping,
                               sizeof(overlapping) / sizeof(overlapping[0])));
    CHECK(diagnostics.errors == 1);
    CHECK(strstr(diagnostics.last_message, "aliases input") != NULL);
    {
        static const char preserved[] = "static int second_input = 2;\n";
        FILE *file = fopen("tests/fixtures/batch-overlap/sub/a.c", "rb");
        CHECK(file != NULL);
        if (file) {
            size_t count = fread(contents, 1, sizeof(contents), file);
            CHECK(fclose(file) == 0);
            CHECK(count == sizeof(preserved) - 1);
            CHECK(memcmp(contents, preserved, sizeof(preserved) - 1) == 0);
        }
    }

    options.input_root = "examples";
    options.output_root = "build/batch-collision";
    CHECK(!noc_transform_files(&context,
                               &options,
                               duplicates,
                               sizeof(duplicates) / sizeof(duplicates[0])));
    CHECK(diagnostics.errors == 2);
    CHECK(strstr(diagnostics.last_message, "same output") != NULL);

    options.output_root = "build/batch-escape";
    CHECK(!noc_transform_files(&context,
                               &options,
                               escaping,
                               sizeof(escaping) / sizeof(escaping[0])));
    CHECK(diagnostics.errors == 3);
    CHECK(strstr(diagnostics.last_message, "escaping path component") != NULL);

    (void)remove("build/batch-preflight/ide/app.c");
    options.output_root = "build/batch-preflight";
    CHECK(!noc_transform_files(&context,
                               &options,
                               late_invalid,
                               sizeof(late_invalid) / sizeof(late_invalid[0])));
    CHECK(diagnostics.errors == 4);
    CHECK(strstr(diagnostics.last_message, "outside input root") != NULL);
    {
        FILE *file = fopen("build/batch-preflight/ide/app.c", "rb");
        CHECK(file == NULL);
        if (file) fclose(file);
    }
#ifdef _WIN32
    {
        const char *drive_input[] = {"C:\\src\\app.c"};
        const char *unc_input[] = {"\\\\server\\share\\app.c"};
        const char *non_ascii_input[] = {"examples/\200/app.c"};
        const char *case_collision[] = {
            "examples/ide/app.c",
            "examples/ide/APP.c",
        };
        const char *separator_collision[] = {
            "examples/ide/app.c",
            "examples\\ide\\app.c",
        };
        options.input_root = "C:";
        options.output_root = "build/batch-windows";
        CHECK(!noc_transform_files(&context, &options, drive_input, 1));
        CHECK(diagnostics.errors == 5);
        options.input_root = "\\\\server\\share";
        CHECK(!noc_transform_files(&context, &options, unc_input, 1));
        CHECK(diagnostics.errors == 6);
        options.input_root = "examples";
        CHECK(!noc_transform_files(&context, &options, non_ascii_input, 1));
        CHECK(diagnostics.errors == 7);
        CHECK(!noc_transform_files(&context, &options, case_collision, 2));
        CHECK(diagnostics.errors == 8);
        CHECK(strstr(diagnostics.last_message, "same output") != NULL);
        CHECK(!noc_transform_files(&context, &options, separator_collision, 2));
        CHECK(diagnostics.errors == 9);
        CHECK(strstr(diagnostics.last_message, "same output") != NULL);
    }
#endif
    noc_context_deinit(&context);
}

static void test_transform_file_with_result(void)
{
    const char *output_path = "build/noc-file-result.c";
    Noc_Context context;
    Noc_Transform_Result result = {0};
    Noc_Transform_Result failed = {0};
    Diagnostic_State diagnostics = {0};
    FILE *file;
    char *written;

    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    CHECK(noc_register_embed_rule(&context, "embed"));
    CHECK(noc_transform_file_with_result(&context,
                                         "examples/embed/app.c",
                                         output_path,
                                         &result));
    CHECK(result.output != NULL && result.output_count > 0);
    CHECK(result.dependency_count == 1);
    CHECK(strcmp(result.dependencies[0], "examples/embed/message.txt") == 0);
    written = (char *)malloc(result.output_count);
    CHECK(written != NULL);
    file = fopen(output_path, "rb");
    CHECK(file != NULL);
    if (file && written) {
        CHECK(fread(written, 1, result.output_count, file) == result.output_count);
        CHECK(memcmp(written, result.output, result.output_count) == 0);
    }
    if (file) CHECK(fclose(file) == 0);
    free(written);
    noc_transform_result_free(&result);
    CHECK(result.output == NULL && result.dependencies == NULL);
    CHECK(remove(output_path) == 0);

    CHECK(!noc_transform_file_with_result(&context,
                                          "examples/embed/app.c",
                                          "examples/embed/app.c",
                                          &failed));
    CHECK(diagnostics.errors == 1);
    CHECK(failed.output == NULL && failed.dependencies == NULL);
    noc_transform_result_free(&failed);
    noc_context_deinit(&context);
}

static void test_file_alias_rejection(void)
{
    static const char contents[] = "int untouched;\n";
    const char *path = "build/noc-alias-source.c";
    FILE *file = fopen(path, "wb");
    char actual[sizeof(contents)] = {0};
    Noc_Context context;
    Diagnostic_State diagnostics = {0};
    CHECK(file != NULL);
    if (!file) return;
    CHECK(fwrite(contents, 1, sizeof(contents) - 1, file) == sizeof(contents) - 1);
    CHECK(fclose(file) == 0);

    noc_context_init(&context);
    noc_context_set_diagnostic(&context, count_diagnostics, &diagnostics);
    CHECK(!noc_transform_file(&context, path, "./build/noc-alias-source.c"));
    CHECK(diagnostics.errors == 1);
    noc_context_deinit(&context);

    file = fopen(path, "rb");
    CHECK(file != NULL);
    if (file) {
        CHECK(fread(actual, 1, sizeof(contents) - 1, file) == sizeof(contents) - 1);
        CHECK(fclose(file) == 0);
        CHECK(memcmp(actual, contents, sizeof(contents) - 1) == 0);
    }
    CHECK(remove(path) == 0);
}

int main(void)
{
    test_ide_metadata_header();
    test_depfile_generation();
    test_command_signature();
    test_batch_transformation();
    test_transform_file_with_result();
    test_file_alias_rejection();
    return finish_suite("artifacts");
}
