/* Generated by noc.h 0.23.0. Do not edit. */
#ifndef NOC_IDE_METADATA_H_INCLUDED
#define NOC_IDE_METADATA_H_INCLUDED

#define NOC_IDE_SCHEMA_VERSION 2
#define NOC_IDE_NOC_VERSION "0.23.0"
#define NOC_IDE_DIALECT_NAME "project"
#define NOC_IDE_RULE_COUNT 4

#define NOC_IDE_RULE_0_NAME "square"
#define NOC_IDE_RULE_0_TRIGGER_KIND 0
#define NOC_IDE_RULE_0_TRIGGER_KIND_NAME "at-name"
#define NOC_IDE_RULE_0_TRIGGER "@square"
#define NOC_IDE_RULE_0_ENABLED 1
#define NOC_IDE_RULE_0_SCOPE 1
#define NOC_IDE_RULE_0_SCOPE_NAME "expression"
#define NOC_IDE_RULE_0_SYNTAX "@square(expression)"
#define NOC_IDE_RULE_0_DESCRIPTION "Evaluate the product of an expression with itself."

#define NOC_IDE_RULE_1_NAME "repeat"
#define NOC_IDE_RULE_1_TRIGGER_KIND 1
#define NOC_IDE_RULE_1_TRIGGER_KIND_NAME "pattern"
#define NOC_IDE_RULE_1_TRIGGER "repeat"
#define NOC_IDE_RULE_1_ENABLED 1
#define NOC_IDE_RULE_1_SCOPE 2
#define NOC_IDE_RULE_1_SCOPE_NAME "statement"
#define NOC_IDE_RULE_1_SYNTAX "repeat(count) { statements }"
#define NOC_IDE_RULE_1_DESCRIPTION "Repeat a statement block count times."

#define NOC_IDE_RULE_2_NAME "counter"
#define NOC_IDE_RULE_2_TRIGGER_KIND 0
#define NOC_IDE_RULE_2_TRIGGER_KIND_NAME "at-name"
#define NOC_IDE_RULE_2_TRIGGER "@counter"
#define NOC_IDE_RULE_2_ENABLED 1
#define NOC_IDE_RULE_2_SCOPE 3
#define NOC_IDE_RULE_2_SCOPE_NAME "declaration"
#define NOC_IDE_RULE_2_SYNTAX "@counter(name);"
#define NOC_IDE_RULE_2_DESCRIPTION "Declare a file-local integer counter initialized to zero."

#define NOC_IDE_RULE_3_NAME "private"
#define NOC_IDE_RULE_3_TRIGGER_KIND 0
#define NOC_IDE_RULE_3_TRIGGER_KIND_NAME "at-name"
#define NOC_IDE_RULE_3_TRIGGER "@private"
#define NOC_IDE_RULE_3_ENABLED 1
#define NOC_IDE_RULE_3_SCOPE 4
#define NOC_IDE_RULE_3_SCOPE_NAME "attribute"
#define NOC_IDE_RULE_3_SYNTAX "@private declaration"
#define NOC_IDE_RULE_3_DESCRIPTION "Give a declaration internal linkage."

#endif /* NOC_IDE_METADATA_H_INCLUDED */
